
services:
#  user-service:
#    build:
#      context: ./microservices/user-service
#    ports:
#      - "8081:8080"  # контейнер внутри слушает 8080, снаружи доступен как 8081
#    environment:
#      DB_HOST: postgres
#      DB_PORT: 5432
#      DB_USER: postgres
#      DB_PASSWORD: postgres
#      DB_NAME: olx
#    depends_on:
#      - postgres
#
#  product-service:
#    build:
#      context: ./microservices/product-service
#    ports:
#      - "8082:8080"
#    environment:
#      # при необходимости можешь передать URL user-service сюда
#      USER_SERVICE_URL: http://user-service:8080
#    depends_on:
#      - user-service
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: olx
    depends_on:
      - postgres
    restart: always

  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: olx
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
